<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <None Remove="Assets\PlayRoundersLogo.svg" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\PlayRoundersLogo.svg" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LeagueStack.Abstractions\LeagueStack.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>LeagueStack.Tenant.PlayRounders</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
