<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>LeagueStack.Tenant.SimpleCricket</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LeagueStack.Abstractions\LeagueStack.Abstractions.csproj" />
  </ItemGroup>

</Project>
